name: Cek Syntax PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    name: Validasi Syntax PHP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout kode
        uses: actions/checkout@v3

      - name: 🔧 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: 🧪 Cek Syntax Semua File PHP
        run: |
          echo "Mengecek file PHP di project..."
          find . -type f -name "*.php" -exec php -l {} \;
